### PR TITLE
Add the new cert-manager members

### PR DESCRIPTION
**Pull request by maelvls**
Might be worth adding @irbekrm and me to the list of owners

Signed-off-by: Maël Valais <mael@vls.dev>

### CODE REVIEW

**Comment by maelvls** [comment]
should we do the same for cert-manager's [OWNERS](https://github.com/jetstack/cert-manager/blob/master/OWNERS) too?

**Comment by munnerz** [comment]
Welcome 🎉 

/lgtm
/approve

**Comment by munnerz** [comment]
@irbekrm I sent you an invite to join the github.com/cert-manager org - once you've done that, if you comment `/verify-owners` here again then the PR should merge 😄

**Comment by maelvls** [comment]
Got it!


Le mer. 27 janv. 2021 à 12:55, James Munnelly <notifications@github.com> a
écrit :

**Comment by irbekrm** [comment]
Thank you! 🙏🏼 

/verify-owners

**Pull request merged**
