### PR TITLE
Make v0.16 the main version

### PR DESCRIPTION
**Pull request by meyskens**
Prepare for 0.16 release and v1.0 as being the next

### CODE REVIEW

**Comment by meyskens** [comment]
/hold

hold for release

**Comment by hzhou97** [comment]
https://github.com/cert-manager/website/blob/575eea3cf759e82b0d3107792b77f97e93fb05da/config/_default/params.toml#L3-L6
Why is the default version v0.13?

**Comment by meyskens** [comment]
@wallrj good catch! first time i do the website :D 

@hzhou97 that variable is kind of unused... noticed this too last time

**Pull request merged**
