### PR TITLE
Add kubernetes-replicator to FAQ/Sync Secrets

### PR DESCRIPTION
**Pull request by caspervk**

### CODE REVIEW

**Comment by irbekrm** [comment]
Thank you for the contribution!

I wasn't aware of `kubernetes-reflector`, looks like a cool project!

/ok-to-test
/lgtm
/approve

**Comment by irbekrm** [comment]
It looks like our spell-checker failed on 'tls' and 'kubernetes-replicator' .

Do you think you would be able to change `tls` -> `TLS` and use backticks around `kubernetes-replicator`?

(Alternatively, spellings that we want the spellchecker to not error on can be added to `.spelling` file.

**Comment by caspervk** [comment]
@irbekrm Thanks a lot for taking a look! I added 'kubernetes-replicator' to `.spelling` to allow for consistency with the existing documentation.

**Comment by caspervk** [comment]
@irbekrm Yeah, that's quite a lot of changes to the repo :blush: I added the changes to `content/docs/faq/sync-secrets.md` instead during the rebase

**Pull request merged**
