### PR TITLE
Rename the "Configuration" and "Usage" top-level menu items

### PR DESCRIPTION
**Pull request by inteon**
Based on what was proposed in https://github.com/cert-manager/website/pull/1260

### CODE REVIEW

**Review by wallrj — CHANGES_REQUESTED** [review]
I personally still prefer "Issuing Certificates",
but if you're going to use "Requesting Certificates", then that should also be the title of the Overview / Introduction page for that section:
 * https://deploy-preview-1282--cert-manager-website.netlify.app/docs/usage/

And ideally, the URL path segment  should also change.

**Comment by inteon** [comment]
> I personally still prefer "Issuing Certificates", but if you're going to use "Requesting Certificates", then that should also be the title of the Overview / Introduction page for that section:
> 
> * https://deploy-preview-1282--cert-manager-website.netlify.app/docs/usage/
> 
> And ideally, the URL path segment should also change.

I did not change the URL, because I think it this is the best way to not break any links.

**Comment by inteon** [comment]
@wallrj I updated the content of those pages.

**Review by wallrj — APPROVED** [review]
Ok. As we discussed this morning, merging this will leave the website in an inconsistent state where the section called "Requesting Certificates" contains documents about prometheus metrics.
How about we merge this and the followup PR into a feature branch.
Then the feature branch preview can be presented in #cert-manager-dev for feedback before we make it live.

/lgtm
/hold in case you want to merge this into a feature branch

**Comment by inteon** [comment]
I think it's not too disruptive, I fear that having a feature branch will just complicate things a lot (given that we might want to make more additional changes on master too).
/unhold

**Pull request merged**
