### PR TITLE
Fix zerossl tutorial path

### PR DESCRIPTION
**Pull request by czomo**
Signed-off-by: czomo <tomaszjdul@gmail.com>
Fixing url to zerossl tutorial as well as adding it to current version of docs.

### CODE REVIEW

**Comment by irbekrm** [comment]
Hi @czomo thank you for the PR!

/ok-to-test

**Comment by czomo** [comment]
@irbekrm Could you take a look? I fixed all test

**Comment by czomo** [comment]
Rebased and squashed. Added prerequisite to use cert manager 1.7.3/1.8.2, updated commands

**Comment by czomo** [comment]
@[jakexks](https://github.com/jakexks) Can you take a look? Thanks

**Comment by czomo** [comment]
Anyone can look at it?

**Comment by Fsero** [comment]
@czomo I was looking into how I could use zerossl with cert-manager and landed here (so thanks a lot for writing this up) I would appreciate this doc being included in the public doc of cert-manager as well.

@JoshVanL
@meyskens
@jakexks 
@irbekrm
@maelvls
@SgtCoDFish
@jahrlin
@wallrj
@munnerz

**Comment by JoshVanL** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
