### PR TITLE
Update kubernetes.md: hub.helm.sh -> artifacthub.io

### PR DESCRIPTION
**Pull request by StianOvrevage**

### CODE REVIEW

**Comment by maelvls** [comment]
Thank you so much for updating the chart URL!! 

/ok-to-test

**Comment by StianOvrevage** [comment]
I struggled getting the sign-off to work properly. Feel free to just change the URL in your own code and push. I don't need to retain any copyrights or credits for this :D

**Comment by SgtCoDFish** [comment]
I've pushed manually with a signoff by myself and cleaned up to 1 commit so we can get this merged and you can retain credit on GitHub :+1:

**Review by SgtCoDFish — APPROVED** [review]
/lgtm

(not sure if it'll complain given I signed the commit; let's see :smile: )

**Comment by SgtCoDFish** [comment]
Thanks again for the PR @StianOvrevage - much appreciated :+1:

**Pull request merged**
