### PR TITLE
HTTP01 istio docs (https://github.com/jetstack/cert-manager/pull/3724)

### LINKED ISSUE #542: Document the Istio VirtualService HTTP01  configuration options
In https://cert-manager.io/docs/tutorials/acme/http-validation/ we discuss Ingress configuration but we should also document the new Istio VirtualService features.
Also add a note to a new v1.4 release notes page.

xref https://github.com/jetstack/cert-manager/pull/3724
cc @inteon

### PR DESCRIPTION
**Pull request by inteon**
Updated docs to match changes in https://github.com/jetstack/cert-manager/pull/3724.

fixes #542

### CODE REVIEW

**Comment by inteon** [comment]
blocked by jetstack/cert-manager#3724

**Comment by jakexks** [comment]
Now https://github.com/jetstack/cert-manager/pull/3724 has merged, this should be updated

/assign @inteon

**Comment by inteon** [comment]
This PR is now up-to-date with the changes in https://github.com/jetstack/cert-manager master.
I also changed `scripts/gendocs/generate` and `scripts/verify-lint` so the broken-link checks don't fail.

**Comment by jpweber** [comment]
I was fortunate to find this pr with these docs because I am trying to use this new feature. Looks like the code has been released and the docs update may have been forgotten.

**Comment by inteon** [comment]
@jpweber unfortunately this feature is not yet part of cert-manager. In https://github.com/jetstack/cert-manager/pull/3988, the https://github.com/jetstack/cert-manager/pull/3724 PR was reverted. But there are plans to add this feature again (check 2nd link).

**Pull request closed without merging**
