### PR TITLE
Add release notes for v1.15.3 and update latest cert-manager version

### PR DESCRIPTION
**Pull request by inteon**
- adds release notes for cert-manager v1.15.3
- updates the latest cert-manager version to v1.15.3

### CODE REVIEW

**Review by wallrj — CHANGES_REQUESTED** [review]
Just one small typo.

/approve

**Review by wallrj — APPROVED** [review]
It may be worth noting that this bug does not affect the webhook of the cert-manager community operator,
because it uses an OLM mechanism  for managing webhook certs:
 * https://olm.operatorframework.io/docs/advanced-tasks/adding-admission-and-conversion-webhooks/#certificate-authority-requirements

https://github.com/cert-manager/cert-manager-olm/blob/b4fb78dcb7d29f38601667c73525aa9d52f1669a/hack/fixup-csv#L120-L126

/lgtm
/hold until released

**Review by wallrj — COMMENTED** [review]
May also be worth mentioning that this bug would also affect people using the dynamic TLS certificate for metrics:
 * https://cert-manager.io/docs/devops-tips/prometheus-metrics/#dynamic-certificates

**Comment by inteon** [comment]
This has been released here: https://github.com/cert-manager/cert-manager/releases/tag/v1.15.3

/unhold

**Pull request merged**
