### PR TITLE
Add docs about ingress controller support for default TLS cert

### PR DESCRIPTION
**Pull request by afirth**
From conversation in https://github.com/jetstack/cert-manager/issues/494

### CODE REVIEW

**Comment by meyskens** [comment]
Thanks!

/approve
/lgtm
/ok-to-test

**Comment by afirth** [comment]
- added traefik to .spelling
- sorted .spelling
rebased and squashed

**Comment by afirth** [comment]
Thanks @meyskens !
Spelling failures fixed, just needs another lgtm

**Pull request merged**
