### PR TITLE
Helm install: add hint for installCRDs in both cases

### PR DESCRIPTION
**Pull request by pinguin999**
I wanted the cert-manager without prometheus so I jumped to the second command.
There was the hint for installCRDs missing so I had a hard time installing cert-manager.

### CODE REVIEW

**Comment by irbekrm** [comment]
Thanks @pinguin999 this makes sense to add 👍🏼 

Would you be able to sign your commit https://cert-manager.io/docs/contributing/sign-off/? (The test is failing because of the missing signature)

**Comment by pinguin999** [comment]
> Thanks @pinguin999 this makes sense to add 👍🏼
> 
> Would you be able to sign your commit https://cert-manager.io/docs/contributing/sign-off/? (The test is failing because of the missing signature)

Hope it's working now

**Comment by irbekrm** [comment]
Thank you for making the changes! 
Could you please squash the PR so that it is one signed commit?

**Comment by pinguin999** [comment]
> Thank you for making the changes! Could you please squash the PR so that it is one signed commit?

Sorry I'm to git dump for that.
Should I close this?

**Comment by irbekrm** [comment]
Don't close it, I think it's a useful addition!

You can do it with git rebase, see https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git

You'd just need to `git rebase -i HEAD~3`, and change 'pick' -> 'squash' for the two commits that you want to squash into the third one. After that make sure that it's signed (you can do `git commit --amend --no-edit --signoff`) and then you will need to add `-f` option when you push.

If that doesn't work, I can squash it for you, but I will then appear as a co-author 😄

**Comment by pinguin999** [comment]
Yes, please squash it for me.

**Review by irbekrm — APPROVED** [review]
Thanks @pinguin999 !

/lgtm

**Pull request merged**
