### PR TITLE
Broken Create a Personal access token URL

### PR DESCRIPTION
**Pull request by amithapa**
The url to Create a personal access token is broken. 
This PR is a fix to the broken URL, pointing to the new URL.

### CODE REVIEW

**Review by wallrj — APPROVED** [review]
Thanks @amithapa 

/approve
/lgtm
/override dco

**Comment by SgtCoDFish** [comment]
Hi @amithapa! Thanks for the PR, it looks great.

We need [DCO Signoff](https://cert-manager.io/docs/contributing/sign-off/) on each commit to certify that you have the rights to make the change.

I can sort it out quickly if you'd like, but for me to do that **you'll need to add a comment on this PR saying you want me to do that**, which would indicate your acceptance of the terms of the [DCO Signoff](https://cert-manager.io/docs/contributing/sign-off/)

**Comment by amithapa** [comment]
@SgtCoDFish Thank you! Can you please go ahead and merge the PR.

**Review by SgtCoDFish — APPROVED** [review]
/lgtm

**Pull request merged**
