### PR TITLE
Small typo fix: sates -> states

### PR DESCRIPTION
**Pull request by TBBle**

### CODE REVIEW

**Comment by meyskens** [comment]
Thank you!

/lgtm
/ok-to-test
/approve

**Comment by TBBle** [comment]
```
+++ Running spell check
    content/en/next-docs/installation/compatibility.md
       36 | n a custom CNI on EKS, so the CNIs differ between control 
       43 | Note that since kubelet uses port `10250` by default  

>> 2 spelling errors found in 536 files
```

Not a file I edited, and I can't see the spelling error on the second line anyway.

**Comment by TBBle** [comment]
#273 still.

**Comment by meyskens** [comment]
@TBBle we run our tests in containers leaving no data behind so this is weird... Well now I guess I know what to do this morning

**Comment by meyskens** [comment]
To be retried after #274 merges

**Pull request merged**
