### PR TITLE
Regenerate approver-policy API docs

### PR DESCRIPTION
**Pull request by erikgb**
Also fixing a few bugs in the generate script caused by project restructuring.

### CODE REVIEW

**Comment by inteon** [comment]
/approve
/lgtm
Thanks for fixing the script and keeping the generated docs up-to-date.

**Comment by erikgb** [comment]
@inteon Any idea how to fix the failing build? The error message isn't clear to me.

**Comment by inteon** [comment]
@erikgb I see the following error: `Expected a closing tag for \`<td>\` (153:9-153:13)`
This might be caused by an unescaped tag or something.
Will investigate this further.

**Comment by inteon** [comment]
@erikgb this line seems to be broken: https://github.com/cert-manager/website/blob/5e67a122a5bd96c50c9a6ac037de91c55539e240/content/docs/policy/approval/approver-policy/api-reference.md?plain=1#L168
This might be a bug in the docs generator, but feel free to just fix the generated code if you do not want to root cause this.

**Comment by erikgb** [comment]
> This might be a bug in the docs generator, but feel free to just fix the generated code if you do not want to root cause this.

Modifying something generated feels wrong. I'll try to get to the bottom of this. Any pointers would be appreciated.

**Comment by erikgb** [comment]
Finally! It works now. 🎉 PTAL!

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

Looks good! Thanks for this 😁 

https://deploy-preview-1415--cert-manager-website.netlify.app/docs/policy/approval/approver-policy/api-reference/

**Pull request merged**
