### PR TITLE
fix: navigation menu hiding search results

### LINKED ISSUE #1082: Navigation menu hiding search results on mobile devices
# Navigation menu hiding search results on mobile devices
## Issue Description

The ham-menu persists even after clicking the search button, eventually hiding the desired search results.

## Tested on
1. **Chrome** and **Firefox** on Android mobile.

## Screenshots

**Actual behavior**

actual

**Expected behavior**

Expected

### PR DESCRIPTION
**Pull request by code-reaper08**
Fixes #1082 

Signed-off-by: Vishwa R <v.i.s.h.w.a.08.11.2001@gmail.com>

### CODE REVIEW

**Comment by code-reaper08** [comment]
Hello @meyskens 😄
This PR hopes to fix the issue #1082

Tested the same on devtools too!

**Comment by code-reaper08** [comment]
Hello @meyskens 👋 
Just thought to remind you on this PR here.
Will help a lot for me, if you have a look.

Thanks!

**Review by wallrj — APPROVED** [review]
Thanks @code-reaper08  and apologies for the delayed reply.

I visited cert-manager.io on a Samsung phone and recreated the problem and then visited the netlify PR preview site and observed that the search menu is now fully visible.

@relativelyrehan  This seems like a simpler solution than https://github.com/cert-manager/website/pull/1102 but thank you both for helping to fix this problem.

/ok-to-test
/approve
/lgtm

**Comment by relativelyrehan** [comment]
@wallrj @code-reaper08 you're welcome. I just want to point out one little thing. My PR along with solving UI issues also helps with the UX issue as in my solution I made the menu alert to outside clicks such that the menu closed not only on tapping at hamburger but with tapping outside the container too. Nonetheless, happy to help 😊

**Comment by wallrj** [comment]
> @wallrj @code-reaper08 you're welcome. I just want to point out one little thing. My PR along with solving UI issues also helps with the UX issue as in my solution I made the menu alert to outside clicks such that the menu closed not only on tapping at hamburger but with tapping outside the container too. Nonetheless, happy to help blush

Ah, I didn't appreciate that. I only clicked on the Algolia "cancel" button when I was testing.

**Comment by code-reaper08** [comment]
> @wallrj @code-reaper08 you're welcome. I just want to point out one little thing. My PR along with solving UI issues also helps with the UX issue as in my solution I made the menu alert to outside clicks such that the menu closed not only on tapping at hamburger but with tapping outside the container too. Nonetheless, happy to help 😊

That was really a nice observation @relativelyrehan 🤝💥

**Pull request merged**
