### PR TITLE
Use DocSearch

### PR DESCRIPTION
**Pull request by meyskens**
This is a PR for using Algolia's DocSearch instead of InstantSearch.

The configuration is at https://github.com/algolia/docsearch-configs/blob/master/configs/cert-manager.json

This PR is now ready for full review

### CODE REVIEW

**Comment by meyskens** [comment]
Version based indexing added in https://github.com/algolia/docsearch-configs/pull/1744
TODO: someway to handle automated version adding

**Comment by munnerz** [comment]
This does look a lot simpler 😄 

That said, it appears to have rendered incorrectly for me on the deploy preview: 
Screenshot 2020-03-03 at 08 52 28

Any ideas? I did try refreshing to see if it was a stale cache but it didn't seem to help!

**Comment by munnerz** [comment]
Also seems like there may be a few dupes in there too 🙈

**Comment by meyskens** [comment]
@munnerz test it on https://deploy-preview-132--cert-manager.netlify.com/docs/ i messed up putting the CSS in the correct place, there might be dupes because I pushed versioning but haven't updated the JS yet

**Comment by munnerz** [comment]
Nice! Yes, way better 😄 

Screenshot 2020-03-03 at 09 00 55

**Comment by meyskens** [comment]
Index for 0.13 added in https://github.com/algolia/docsearch-configs/pull/1788

**Comment by munnerz** [comment]
Do we want to index `next-docs` too? We don't actually currently index this today as it doesn't match the regex in the `scripts/index` file. Could be done later, and from what I understand only requires a change over in the algolia repo and not here

**Comment by munnerz** [comment]
Also, when searching here: https://deploy-preview-132--cert-manager.netlify.com/v0.12-docs/ I expected to see some results (as only v0.13 is being added here, v0.12 already existed: https://github.com/algolia/docsearch-configs/pull/1788/files)

Is that expected?

**Comment by meyskens** [comment]
@munnerz `facetFilters: ["version:view-132--cert-manager.netlify.com/v0.12-docs"]"}]}`
seems to have made a bug with the deploy preview, taking a look

**Comment by meyskens** [comment]
Fixed this by using the path specified by the browser.

**Pull request merged**
