### PR TITLE
Remove the now duplicate "project-maturity" page

### PR DESCRIPTION
**Pull request by maelvls**
Looks like the [supported-releases](https://cert-manager.io/docs/installation/supported-releases/) page now covers what is in [project-maturity](https://cert-manager.io/docs/concepts/project-maturity/).

I suggest we remove the project-maturity page, and we redirect it to supported-releases to avoid link breakage:

> https://deploy-preview-563--cert-manager.netlify.app/docs/concepts/project-maturity/
> redirects to
> https://deploy-preview-563--cert-manager.netlify.app/docs/installation/supported-releases/

The redirection using `aliases` (Hugo-specific) works with this meta tag (as opposed to a 301 Redirect):

```html
<meta http-equiv="refresh" content="0; url=https://cert-manager.io/docs/installation/supported-releases/" />
```

Full example:

```sh
curl -i https://deploy-preview-563--cert-manager.netlify.app/docs/concepts/project-maturity/
```
returns
```http
HTTP/2 200
cache-control: public, max-age=0, must-revalidate
content-length: 379
content-type: text/html; charset=UTF-8
date: Tue, 25 May 2021 13:59:52 GMT
etag: "640337afa4659b81990e322235d90dc6-ssl"
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-robots-tag: noindex
x-nf-request-id: 25980de5-8036-4233-9468-bdecfc27be67
server: Netlify
age: 2

<!DOCTYPE html>
<html>
  <head>
    <title>https://cert-manager.io/docs/installation/supported-releases/</title>
    <link
      rel="canonical"
      href="https://cert-manager.io/docs/installation/supported-releases/"
    />
    <meta name="robots" content="noindex" />
    <meta charset="utf-8" />
    <meta
      http-equiv="refresh"
      content="0; url=https://cert-manager.io/docs/installation/supported-releases/"
    />
  </head>
</html>
```

cc @munnerz

### CODE REVIEW

**Comment by munnerz** [comment]
Hm - I've not seen the `aliases` configuration before... we have previously used `_redirects` here for this purpose: https://github.com/cert-manager/website/blob/master/_redirects (which is a netlify thing for configuring 301 redirects)

**Comment by maelvls** [comment]
I added a bit of information about how this aliases works; I use it extensively since it does not require configuring any reverse proxies like Netflies' one, which means it is compatible with dumb CDNs like GitHub Pages or Cloudflare Pages 😀

I added a redirect in `_redirect` and remove the `aliases`.

**Comment by SgtCoDFish** [comment]
this obsoletes https://github.com/cert-manager/website/issues/305, which I'll go ahead and close.

**Comment by SgtCoDFish** [comment]
/lgtm

This is a good improvement and it's great that the old URL will be preserved with a redirect :+1:

**Pull request merged**
