### PR TITLE
link the forcing_renewal article into the FAQ

### PR DESCRIPTION
**Pull request by tpo**
I think that after the [2020.02.29 CAA Rechecking Bug](https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591) a lot of people will want to know how a renewal of a certificate can be forced. This should document the process.

### CODE REVIEW

**Comment by tpo** [comment]
this pull request depends on this other pull request here: https://github.com/cert-manager/website/pull/136
I'm sorry I've messed that up, however it's late (and I really should go to sleep) and I think this will be a FAQ very soon, so I thought I rather document it now than tomorrow.

**Comment by meyskens** [comment]
I am going to close this request as we released a tool to assist with this. More info is at https://github.com/jetstack/cert-manager/issues/2651

**Comment by tpo** [comment]
> I am going to close this request as we released a tool to assist with this. More info is at [jetstack/cert-manager#2651](https://github.com/jetstack/cert-manager/issues/2651)

@meyskens cool, thanks!

**Pull request closed without merging**
