### PR TITLE
cert-manager website refresh

### PR DESCRIPTION
**Pull request by SgtCoDFish**
This PR adds the cert-manager website refresh.

This has been reviewed in several sessions previously; it's not expected that anyone would actually seriously review the changes made here.

There will be some teething troubles with this site; there'll be a few broken links when we merge. They can be fixed over time!

Thanks to https://github.com/C-Mejlak and https://github.com/PatrickHeneise for their work on this too!

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
/hold

Don't want this to merge until we're good and ready!

**Comment by maelvls** [comment]
I'll peruse the 2,640 files now.

**Review by jakexks — APPROVED** [review]
/lgtm

Rationale for LGTM: Much of this has been reviewed already, but this is a squashed commit
We can't continue without this being merged
@SgtCodFish is on hand to fix any issues as they appear

**Pull request merged**
