### PR TITLE
update twitter icon to x [Fixes #1321]

### LINKED ISSUE #1321: Request to Update Twitter Icon to X
⭐ Suggestion
Issue Description
The Twitter logo has been updated recently and hasn't been updated on the site.

Steps to Reproduce

Step 1: Go to  header and footer section and see twitter old lcon

Current Behaviour
Screenshot 2023-10-07 at 4 48 28 PM

Screenshot 2023-10-07 at 4 48 33 PM

Expected Behaviour
The Twitter logo should be changed to X.

Screenshot 2023-10-07 at 4 48 39 PM

Screenshot 2023-10-07 at 4 48 45 PM

### PR DESCRIPTION
**Pull request by sarthak-kumar-shailendra**
Fixing the issue [fixes https://github.com/cert-manager/website/issues/1321]

hacktober

Changed the svg of twitter icon to x
Screenshot 2023-10-07 at 4 48 39 PM
Screenshot 2023-10-07 at 4 48 45 PM

### CODE REVIEW

**Review by inteon — COMMENTED** [review]
Thanks for your contribution!
/lgtm
/approve

**Comment by sarthak-kumar-shailendra** [comment]
@inteon can you add hacktoberfest-accepted label to this PR

**Comment by inteon** [comment]
@sarthak-kumar-shailendra I added the label, although I don't think it is strictly required for `hacktoberfest`.

**Comment by sarthak-kumar-shailendra** [comment]
Thanks a lot! Actually, it was showing not accepted in hacktoberfest for this PR.

**Pull request merged**
