### PR TITLE
Add the "life of a certificate" diagram

### PR DESCRIPTION
**Pull request by maelvls**
This PR is part of the work in https://github.com/cert-manager/website/issues/426. This diagram is not done, but I propose to release an initial version instead of waiting further.

| Preview | https://deploy-preview-582--cert-manager.netlify.app/docs/concepts/certificate/ |
|-|-|

cc @irbekrm

### CODE REVIEW

**Comment by irbekrm** [comment]
Looks great to me already 🥳 🥳 

(I think the correct preview link might be https://deploy-preview-582--cert-manager.netlify.app/docs/concepts/certificate/)


A small nit- I think the `Order` is not removed immediately, but just by the time the next `Order` needs to be created?

Suggestion: 'requestmanager creates CertificateRequest with revision = "1" since its revision is nil' <- perhaps it would make sense to drop the 'since its revision is nil', I imagine it would be either obvious or confusing?

Another suggestion: I think the `Challenge`s are created from `Order.status.authorizations` fields, perhaps worth to move the arrows slightly to indicate this?

Agree that it might make sense to merge this as is though and I think the diagram is great- it should be super helpful to users already.
Please unhold to merge as is if you'd rather do that!

/hold
/approve
/lgtm

**Comment by maelvls** [comment]
poke @irbekrm

**Comment by irbekrm** [comment]
Thanks for the poke 😄 

I think we should merge this, it would give users a lot of value imo.

Thank you for working on this and making it so nice!

/lgtm

/hold cancel

**Pull request merged**
