### PR TITLE
Fix the SVG logo file using the source .ai file

### LINKED ISSUE #369: SVG Broken
The rendering of the cert-mamager SVG logo seems to be broken on recent rendering engines like Chrome beta or some releases of Firefox.

### PR DESCRIPTION
**Pull request by maelvls**
Fixes #369

### CODE REVIEW

**Comment by jakexks** [comment]
I think this should be cherry-picked all the way back, but maybe for sanity's sake just back to 0.16?

**Comment by maelvls** [comment]
before vs. after:
before after

**Pull request merged**
