### PR TITLE
Add doc reference for AWS Private CA issuer

### PR DESCRIPTION
**Pull request by sudhindra-hub**
Signed-off-by: Sudhindra Tirupati Nagaraj <sudhip1234@yahoo.com>

### CODE REVIEW

**Comment by JoshVanL** [comment]
Need to update .spelling

**Comment by sudhindra-hub** [comment]
looks like a spelling error tripped the verify?

```
+++ Running spell check
    content/en/docs/configuration/external.md
       28 | - [awspca-issuer](https://github.com/codingvir 

>> 1 spelling error found in 536 files
```

**Comment by JoshVanL** [comment]
@sudhindra-hub indeed, the file you're looking for is `.spelling` at the repo root

**Comment by sudhindra-hub** [comment]
@JoshVanL I am not sure what spelling 

> @sudhindra-hub indeed, the file you're looking for is `.spelling` at the repo root

thanks!

**Comment by JoshVanL** [comment]
Think it was the word `awspca`. Should be okay now though :)

/lgtm

**Comment by sudhindra-hub** [comment]
> Think it was the word `awspca`. Should be okay now though :)
> 
> /lgtm

Sorry for the revert again. I reverted to the old spelling to keep naming consistent with actual issuer.

**Comment by JoshVanL** [comment]
Yeah no worries! That's a good shout

**Comment by JoshVanL** [comment]
Thanks again @sudhindra-hub !
Always great to see external issuers

**Pull request merged**
