### PR TITLE
Make sure all intended headings have anchors

### PR DESCRIPTION
**Pull request by gerrywastaken**
Fixes the code part of https://github.com/cert-manager/website/issues/484

### CODE REVIEW

**Comment by gerrywastaken** [comment]
Good idea. I only assigned jakexks because the bot told me to: https://github.com/cert-manager/website/pull/491#issuecomment-808730877

**Comment by maelvls** [comment]
Thanks for the fix!! 🙏 

/lgtm 

(Jake is on vacation I think 😅)

**Pull request merged**
