### PR TITLE
Update ingress-class-compatibility.md

### PR DESCRIPTION
**Pull request by interone-ms**
Per https://kubernetes.github.io/ingress-nginx/#how-to-easily-install-multiple-instances-of-the-ingress-nginx-controller-in-the-same-cluster, the nginx-ingress controller needs a bit more parameters set.

Signed-off-by: Marco Schuster <marco.schuster@interone.de>

### CODE REVIEW

**Review by SgtCoDFish — APPROVED** [review]
The documentation for ingressClassByName is lacking a little so it's been hard to review this :sweat_smile: 

I think [this](https://github.com/kubernetes/ingress-nginx/blob/fc58e92b3951bd313a36eba227933bb4e931cfbd/internal/ingress/controller/ingressclass/ingressclass.go#L48-L50) is the best definition there is. I've not seen much in the code to help.

In any case this change seems harmless so I'll approve - thank you for raising it! :grin: 

/lgtm
/approve

**Comment by interone-ms** [comment]
Sorry for leaving the context out. For posterity:

1. `controller.ingressClassByName` causes the controller template (https://github.com/kubernetes/ingress-nginx/blob/4b4895b53bb5fd00874deeeb914d5d36fd19556e/charts/ingress-nginx/templates/_params.tpl) to add the flag `--ingress-class-by-name=true` to be added to the nginx controller pod.
2. The flag ends up recognized in the controller code at https://github.com/kubernetes/ingress-nginx/blob/89ed571d2a8c7c2486e9671808e27a7cfbe3b40d/internal/ingress/controller/store/store.go#L515, where it allows the controller to recognize Ingress objects that *only* have the old-style `kubernetes.io/ingress.class` annotation set.

**Comment by SgtCoDFish** [comment]
Oh no need to apologise, I was struggling with the docs for ingress-nginx!

Thank you for the additional context though :heart:

**Pull request merged**
