### PR TITLE
Link to the official Flux example repo and remove unnecessary --crds flags from example

### PR DESCRIPTION
**Pull request by wallrj**
**Preview**: https://deploy-preview-1343--cert-manager-website.netlify.app/docs/installation/continuous-deployment-and-gitops/#using-the-flux-helm-controller

1. Linked to official Flux example repo

   In https://github.com/fluxcd/flux2/discussions/3009#discussioncomment-7508833 @stefanprodan wrote:
   > cert-manager is now fully integrated in the official Flux example repo, including deploying Cluster Issuers in the right 
   order, after cert-manager CRDs and controller have been installed.
   > it would great if you could add a link to https://github.com/fluxcd/flux2-kustomize-helm- 
  example/blob/main/infrastructure/controllers/cert-manager.yaml for a GitOps example

2. Removed `--crds CreateReplace` because cert-manager CRDs do not use the Helm `crds/` directory.

   In https://github.com/fluxcd/flux2/discussions/3009#discussioncomment-7510213 @stefanprodan wrote:
   > CreateReplace will not do anything if there is no crds dir inside the chart.

### CODE REVIEW

**Review by hawksight — APPROVED** [review]
Appreciate the research on this :+1: 

/lgtm

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @wallrj 🥇

**Comment by wallrj** [comment]
@inteon `/lgtm` doesn't work if you add a trailing remark, unlike `/hold because ...`. Not sure why.

**Pull request merged**
