### PR TITLE
[GSOD] Define our audiences

### PR DESCRIPTION
**Pull request by wallrj**
@mehak151 I've started writing down descriptions of each of the target audiences, as discussed. 

Please take a look and I'll try and write some more tomorrow.

FYI @maelvls and I got this idea of defining our audiences after reading [Content planning in the Microsoft documentation guide](https://docs.microsoft.com/en-us/style-guide/content-planning)

Sorry for the delay. 

/cc @maelvls

### CODE REVIEW

**Comment by maelvls** [comment]
I am surprised to see that I haven't reviewed this PR.

/lgtm

**Comment by maelvls** [comment]
I'll unhold so that it disappears from my list of PRs to be reviewed. 😅 

/unhold

**Review by maelvls — APPROVED** [review]
/lgtm

**Comment by wallrj** [comment]
@maelvls Fixed spelling errors. PTAL.

**Pull request merged**
