### PR TITLE
Reword intro for csi-driver-spiffe

### PR DESCRIPTION
**Pull request by SgtCoDFish**
Fix some broken English / grammar, and rewords things slightly

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
/hold

This is blocked behind https://github.com/cert-manager/csi-driver-spiffe/pull/25 which will update the examples.

Once that PR merges, I'll update the docs page to point at the new updated examples (since they're - correctly - referred to by commit SHA, it'll need to be updated)

**Comment by SgtCoDFish** [comment]
/unhold

I added a hold in a previous comment, but then decided to go in a different direction

**Review by wallrj — APPROVED** [review]
Thanks for making this documentation clearer.
I read the suggested commands and they look good to me, but I did not test them locally.

/lgtm

**Comment by SgtCoDFish** [comment]
Linking here; https://github.com/cert-manager/csi-driver-spiffe/pull/25

That PR applies the same changes to the relevant part of the csi-driver-spiffe README

**Pull request merged**
