### PR TITLE
add acme-http01-solver-nameservers flag documentation

### PR DESCRIPTION
**Pull request by Adphi**
This pull request add documentation to the acme-http01-solver-nameservers flag (https://github.com/jetstack/cert-manager/pull/4287).

### CODE REVIEW

**Review by wallrj — APPROVED** [review]
Thanks @Adphi 

This is an as-yet unreleased feature, so needs to be rebased and merged into `release-next` branch rather than `master`.


/ok-to-test

**Comment by Adphi** [comment]
@wallrj can you help me fix the test, please ?

**Comment by wallrj** [comment]
```sh
$ ./scripts/verify-lint 

...
+++ Running spell check
    content/en/docs/configuration/acme/http01/_index.md
      339 | cert-manager will perform reachability tests before attempting a HTT 
      341 | .conf` to query the challenge url. 

>> 2 spelling errors found in 575 files
```
The syntax highlighting is lost in the CI results.
See 
 * https://github.com/cert-manager/website/issues/802


But the failed words are `url` and `reachability`.

I tried pushing this change to your branch, but it failed. Here's the patch for you to apply.

```diff

diff --git a/.spelling b/.spelling
index e5add0a..db5ecf3 100644
--- a/.spelling
+++ b/.spelling
@@ -293,6 +293,7 @@ prioritise
 propagations
 publicised
 reStructuredText
+reachability
 rebase
 reissuance
 reflector
diff --git a/content/en/docs/configuration/acme/http01/_index.md b/content/en/docs/configuration/acme/http01/_index.md
index dfac0c4..5eecdcf 100644
--- a/content/en/docs/configuration/acme/http01/_index.md
+++ b/content/en/docs/configuration/acme/http01/_index.md
@@ -338,7 +338,7 @@ This field has the same meaning as the
 
 cert-manager will perform reachability tests before attempting a HTT01
 challenge.  By default cert-manager will use the recursive nameservers taken
-from `/etc/resolv.conf` to query the challenge url.
+from `/etc/resolv.conf` to query the challenge URL.
 
 If this is not desired (for example with split-horizon DNS), the cert-manager
 controller exposes a flag that allows you alter this behavior:
@@ -359,4 +359,3 @@ with `--set`:
 ```bash
 --set 'extraArgs={--acme-http01-solver-nameservers=8.8.8.8:53\,1.1.1.1:53}'
 ```

```

**Review by wallrj — APPROVED** [review]
Thanks @Adphi  for all your work on this feature.

/lgtm

PS If you have time, please try out https://github.com/jetstack/cert-manager/releases/tag/v1.7.0-beta.0 and let us know if you find any bugs.

**Pull request merged**
