### PR TITLE
Adds comment to SecretTemplate about feature gate

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>

/hold

Adds comment around SecretTemplate feature gate.

Pending https://github.com/jetstack/cert-manager/pull/4638

### CODE REVIEW

**Review by wallrj — CHANGES_REQUESTED** [review]
@JoshVanL I think you removed the feature gate for SecretTemplateApply so this needs updating.

**Comment by JoshVanL** [comment]
@wallrj sorry for being slow and thanks for the ping. Please take another look

**Review by wallrj — APPROVED** [review]
Thanks @JoshVanL 

/approve
/lgtm

**Pull request merged**
