### PR TITLE
Roll versions forward for v1.4 release

### PR DESCRIPTION
**Pull request by jakexks**

### CODE REVIEW

**Review by wallrj — APPROVED** [review]
Some remaining things that need updating
 * https://cert-manager.io/docs/usage/kubectl-plugin/
 * https://cert-manager.io/docs/installation/supported-releases/

Here or in a followup PR and unhold

/approve
/lgtm
/hold

**Comment by jakexks** [comment]
Thanks @wallrj 

Supported releases - https://github.com/cert-manager/website/pull/606

kubectl plugin I'll do in here

**Review by wallrj — APPROVED** [review]
/approve 
/lgtm

Thanks Jake.

**Pull request merged**
